site_name:           Neuropsydia
repo_url:            https://github.com/neuropsychology/Neuropsydia
site_description:    Description
site_author:         Dominique Makowski
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Functions:
  - Title 1: tutorials/page1.md
  - Title 2: tutorials/page2.md
